### ISSUE TITLE
question about the 

### ISSUE THREAD

**Issue by raywang0563** [Patent2net/P2N-v3#1]
Dear Sir/Madam,
      I have installed P2N-v3 successfully according to the installation instruction. However, when I run "runp2nsingle.bat" containing the following commands:
conda activate P2N & p2n run --config=../banana_peel.cql --with-family

some error messages appear as follows:
2019-07-11 19:01:55,861 [p2n.util                 ] INFO   : Running command "python OPSGatherPatentsv2.py ../banana_peel.cql"
Traceback (most recent call last):
  File "OPSGatherPatentsv2.py", line 71, in <module>
    configFile = LoadConfig()
  File "C:\Users\rdwang\Anaconda3\envs\P2N\lib\site-packages\patent2net-3.0.0.dev6-py3.6.egg\Patent2Net\P2N_Config.py", line 148, in LoadConfig
    return P2NConfig()
  File "C:\Users\rdwang\Anaconda3\envs\P2N\lib\site-packages\patent2net-3.0.0.dev6-py3.6.egg\Patent2Net\P2N_Config.py", line 41, in __init__
    content = self.readInputFile()
  File "C:\Users\rdwang\Anaconda3\envs\P2N\lib\site-packages\patent2net-3.0.0.dev6-py3.6.egg\Patent2Net\P2N_Config.py", line 107, in readInputFile
    return open(arg, "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: '../banana_peel.cql'
2019-07-11 19:01:56,863 [p2n.util                 ] **ERROR  : Command "python OPSGatherPatentsv2.py ../banana_peel.cql" failed with return code 1**

I'd appreciate if you can let me know what wrong with it. Thank you.

Ray

**Comment by Patent2net** [comment]
Hi Ray,
Damn, this should not append. 
the batch script tries to run the config file "../banana_peel.cql". '../' points the root of P2N install directory. 
1. Please edit a config file as you wich (you have many examples in the RequestsSets directory
2. name it as you wish (Name.cql) and store it in the same dir
3. modify runp2nsingle.bat to adapt your config file as follow (changing Name.cql with the correct one):
conda activate P2N & p2n run --config=../RequestsSets/Name.cql --with-family

This should be ok then if you followed the step of key/pass creation from the EPO API
Best,

**Comment by raywang0563** [comment]
Yes, the problem has been solved according to your suggestion. By the way, how many search terms can be used for each request in the config file? Five search terms was workable, but 20 was not workable. Thank you.

**Comment by Quoniam** [comment]
Hi Ray,
This is due to Espacenet limitations
https://worldwide.espacenet.com/help?locale=en_EP&method=handleHelpTopic&topic=limitations
The way to overcome this limitation with Patent2Net is described here
http://patent2netv2.vlab4u.info/dokuwiki/doku.php?id=user_manual:fusion
Best regards
